---
- name: Disable password auth for SSH
  hosts: all
  become: true
  vars_files: ~/.ansible/inventory/vaulted_vars.yml

  tasks:
    - name: Change /etc/ssh/sshd_config
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '(#|)PasswordAuthentication yes'
        line: 'PasswordAuthentication no'
        backrefs: true
      when: ansible_os_family == "Debian"
