---
- name: Change Cloudflare API key
  hosts: proxies
  gather_facts: false
  vars_files: ~/.ansible/inventory/vaulted_vars.yml

  vars_prompt:
    - name: api_key_input
      prompt: "Enter the new API key"
      private: yes

  tasks:
    - name: Update API key in files
      lineinfile: # Use variable "envfile" of each host for path of file to be changed
        path: "{{ hostvars[inventory_hostname]['envfile'] }}"
        regexp: "^CLOUDFLARE_API_KEY=.*"
        line: "CLOUDFLARE_API_KEY={{ api_key_input }}"
